[package]
name = "rollkit"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky.workspace = true
rand = "0.9.2"

[workspace]
members = [
    "rollkit_repl",
]

[workspace.dependencies]
chumsky = { version = "0.11.2", features = ["pratt"] }
