[package]
name = "rollkit_repl"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky.workspace = true
rollkit = { path = "..", version = "0.1.0", features = ["std"] }
rustyline = "17.0"
yansi = "1.0.1"
